### ISSUE TITLE
Do I always have to have attrs to run kaiba?

### ISSUE THREAD

**Issue by ChameleonTartu** [kaiba-tech/kaiba#95]
I tried using `kaiba` on Mac with blank project, no dependencies.

I received this issue
> ImportError: cannot import name 'dataclass' from 'attr' (/Users/dc/Library/Caches/pypoetry/virtualenvs/whatever-project-py3.10/lib/python3.10/site-packages/attr.py)

It worked fine after installing `attrs` - I initially installed `attr`, not `attrs`. 

Do I always need to install this dependency? Can it be bundled with `kaiba`?

**Comment by thomasborgen** [comment]
I'm having troubles reproducing this. 

Testing with py 3.10 like this works:

```sh
pyenv use 3.10.6
rm -rf .venv
poetry install
poetry run pytest
```

We also don't have a direct requirement to attrs, I think if its there its through `pydantic` or `returns`. 
Please let me know if you can reproduce it again.
