### ISSUE TITLE
Is it possible to iterate over data without a root?

### ISSUE THREAD

**Issue by ChameleonTartu** [kaiba-tech/kaiba#97]
I have a JSON file as a list. Is it possible to iterate and process it if there is no root?

```
[
  {
    "name": "Sam",
    "age": 12
  },
  ...
  {
    "name": "Bill",
    "age": 45
  }
]
```

I cannot find it anywhere covered, so asking in case I missed it. Maybe it is a bug in docs? 😅

**Comment by thomasborgen** [comment]
Its not possible at the moment. But it should be. 

There is already an issue for this: https://github.com/kaiba-tech/kaiba/issues/22
so i'm closing this :)
